# Generated by Django 6.0 on 2025-12-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libro_portada_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción disponible'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(default='General', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genero'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='notas',
            field=models.TextField(blank=True, default='No hay observaciones'),
        ),
    ]
